"""一次性 seed：把 spec §3 全集写进 macro_inputs.yaml。零 LLM。可重复运行（upsert 幂等）。

运行：  python3 -m prism.scripts.seed_macro_inputs
"""
from prism.scripts import macro_registry as mr

SLUG = "global-macro-rates-liquidity"
VARIANT = "opus4.8"


def E(name, tier, cadence_type, targets, mechanism, importance, source,
      fetch_method, state, causal_sentence="", lag="同步", alert_series=False,
      alert_band=None):
    e = {
        "name": name, "tier": tier, "cadence_type": cadence_type,
        "targets": targets, "mechanism": mechanism, "importance": importance,
        "source": source, "fetch_method": fetch_method, "state": state,
        "causal_sentence": causal_sentence, "lag": lag,
        "alert_series": alert_series, "monitoring": {"enabled": True},
    }
    if alert_band:
        e["alert_band"] = alert_band
    return e


# 转录规则：
#   层 A/B/C → tier；型 事/行/述 → event/series/policy；
#   目标 R/L/FX → rates/liquidity/fx；机制 CD/CF/CO/CR 原样；
#   重要度 承重/确认/背景 → load_bearing/confirming/background；状态原样。
#   alert_band：六条报警序列先给占位粗档（spec §11 待用户回填精值），
#   delta 为"n 日绝对变动阈值"，z 为"z-score 阈值"。
INPUTS = [
    # ── 3.1 美国 — 增长 / 通胀 / 政策 ──────────────────────────────────────
    E("联邦基金目标区间", "A", "event", ["rates", "liquidity", "fx"], "CD",
      "load_bearing", "FRED", "fred-api", "已有",
      causal_sentence="联邦基金目标区间设定无风险短端利率锚 → 经全曲线与美元定价 → 直接驱动利率/流动性/汇率。"),
    E("FOMC 点阵图(SEP)", "A", "event", ["rates"], "CD",
      "load_bearing", "web(Fed)", "llm-web", "已有",
      causal_sentence="点阵图昭示 FOMC 对政策路径的中位预期 → 经市场重定价远期利率 → 驱动利率。"),
    E("CME FedWatch 隐含路径", "A", "series", ["rates"], "CD",
      "load_bearing", "web(CME)", "llm-web", "已有",
      causal_sentence="期货隐含的降息/加息概率即市场对政策路径的实时定价 → 经远期利率 → 驱动利率。"),
    E("FOMC 声明/纪要", "A", "policy", ["rates", "liquidity"], "CD",
      "load_bearing", "web(Fed)", "llm-web", "新增",
      causal_sentence="声明/纪要措辞变化传递反应函数转向 → 经预期重置远端利率与流动性预期 → 驱动利率/流动性。"),
    E("美联储官员讲话(主席)", "A", "policy", ["rates"], "CD",
      "confirming", "web", "llm-web", "改(原仅注解)",
      causal_sentence="主席讲话前瞻指引调整市场对反应函数的认知 → 经预期重定价 → 驱动利率。"),
    E("非农就业 NFP", "A", "event", ["rates", "fx"], "CD",
      "load_bearing", "FRED", "fred-api", "改(原仅注解)",
      causal_sentence="就业强弱改变 Fed 对劳动力市场松紧的判断 → 经反应函数调整政策路径 → 驱动利率与美元。"),
    E("失业率", "A", "event", ["rates"], "CD",
      "load_bearing", "FRED", "fred-api", "新增",
      causal_sentence="失业率是双重使命的就业侧读数 → 经反应函数（Sahm 触发等）调整政策 → 驱动利率。"),
    E("初请失业金", "A", "event", ["rates"], "CD",
      "confirming", "FRED", "fred-api", "新增", lag="领先(周)",
      causal_sentence="周度初请是劳动力市场最高频前瞻 → 经领先就业拐点改变政策预期 → 驱动利率。"),
    E("JOLTS 职位空缺/离职率", "A", "event", ["rates"], "CD",
      "confirming", "FRED", "fred-api", "新增",
      causal_sentence="空缺/离职率度量劳动力市场紧度（贝弗里奇曲线）→ 经工资与反应函数 → 驱动利率。"),
    E("ISM 制造业 PMI", "A", "event", ["rates", "fx"], "CD",
      "load_bearing", "web", "llm-web", "新增", lag="领先",
      causal_sentence="PMI 领先增长动能 → 经增长预期改变政策路径与风险偏好 → 驱动利率与美元。"),
    E("ISM 服务业 PMI", "A", "event", ["rates"], "CD",
      "confirming", "web", "llm-web", "新增", lag="领先",
      causal_sentence="服务业 PMI 度量占比最大的服务部门动能 → 经增长/通胀预期 → 驱动利率。"),
    E("零售销售", "A", "event", ["rates"], "CD",
      "confirming", "FRED", "fred-api", "新增",
      causal_sentence="零售销售即时反映消费动能 → 经增长与通胀路径预期 → 驱动利率。"),
    E("GDPNow 实时预测", "B", "series", ["rates"], "CO",
      "confirming", "web(亚特兰大联储)", "llm-web", "新增",
      lag="同步(实时拼接)"),
    E("时薪 / ECI", "A", "event", ["rates"], "CD",
      "confirming", "FRED", "fred-api", "新增",
      causal_sentence="工资增速是服务通胀的核心成本推手 → 经通胀粘性影响反应函数 → 驱动利率。"),
    E("核心 PCE", "A", "event", ["rates"], "CD",
      "load_bearing", "FRED", "fred-api", "新增",
      causal_sentence="核心 PCE 是 Fed 首选通胀标尺，分期限作用（短端正/长端可反向），用超预期而非水平触发 → 经反应函数 → 驱动利率。"),
    E("CPI(核心+supercore)", "A", "event", ["rates"], "CD",
      "load_bearing", "FRED", "fred-api", "新增",
      causal_sentence="CPI 核心/supercore 揭示通胀粘性结构 → 经通胀预期与反应函数 → 驱动利率。"),
    E("PCE 三分项(supercore/住房/商品)", "B", "event", ["rates"], "CD",
      "confirming", "FRED", "fred-api", "新增",
      causal_sentence="分项拆解定位通胀来源（住房滞后、supercore 粘）→ 经对通胀路径的判读 → 驱动利率。"),
    E("PPI", "A", "event", ["rates"], "CD",
      "confirming", "FRED", "fred-api", "改(原仅注解)", lag="领先",
      causal_sentence="PPI 是 CPI/PCE 的上游成本前瞻 → 经传导至终端通胀预期 → 驱动利率。"),
    E("WTI 油价(+供给/需求分解)", "A", "series", ["rates", "fx"], "CD",
      "load_bearing", "FRED", "fred-api", "改",
      causal_sentence="油价经能源与运输成本推动 headline 通胀及预期 → 经反应函数 → 驱动利率与美元。"),
    E("5y5y/breakeven 通胀预期", "A", "series", ["rates"], "CD",
      "confirming", "FRED", "fred-api", "新增",
      causal_sentence="盈亏平衡通胀（半内生于利率）度量市场长期通胀锚 → 经名义利率分解 → 驱动利率。"),

    # ── 3.2 美国 — 财政 / 流动性 / 管道 ──────────────────────────────────
    E("国债发行计划 QRA + 票/券构成", "A", "policy", ["liquidity", "rates"], "CD",
      "load_bearing", "web(Treasury)", "llm-web", "改(升级:加构成)",
      causal_sentence="QRA 发行规模与票/券构成决定久期供给与对准备金/RRP 的抽取 → 经期限溢价与净流动性 → 驱动流动性/利率。"),
    E("TGA 余额", "A", "series", ["liquidity"], "CD",
      "load_bearing", "FRED", "fred-api", "改(原仅净流动性内)",
      causal_sentence="TGA 增减直接吸放银行准备金 → 经净流动性 → 驱动流动性。"),
    E("联邦赤字", "B", "event", ["rates"], "CD",
      "background", "FRED", "fred-api", "新增",
      causal_sentence="赤字规模决定中长期国债净供给 → 经期限溢价 → 驱动利率。"),
    E("美联储资产 WALCL(QT 节奏)", "A", "series", ["liquidity", "rates"], "CD",
      "load_bearing", "FRED", "fred-api", "改", lag="同步(周)",
      causal_sentence="QT 缩表节奏决定准备金供给收缩速度 → 经净流动性与期限溢价 → 驱动流动性/利率。"),
    E("RRP 逆回购", "A", "series", ["liquidity"], "CD",
      "confirming", "FRED", "fred-api", "改",
      causal_sentence="RRP 是流动性蓄水池，余额变动反映过剩流动性吸/放 → 经净流动性 → 驱动流动性。"),
    E("净流动性(=资产−TGA−RRP)", "A", "series", ["liquidity"], "CD",
      "load_bearing", "FRED派生", "fred-api", "改(降权重,见§5)",
      causal_sentence="净流动性=资产−TGA−RRP，regime 条件性（RRP 耗尽后才 binding）地度量银行体系可用准备金 → 直接驱动流动性。"),
    E("银行准备金 + 准备金/GDP", "A", "series", ["liquidity"], "CD",
      "load_bearing", "FRED", "fred-api", "新增", lag="同步(周)",
      causal_sentence="准备金水平（相对 GDP）决定体系离稀缺区的距离 → 经回购市场压力阈值 → 驱动流动性。"),
    E("SOFR−IORB / 回购压力", "A", "series", ["liquidity", "rates"], "CD",
      "load_bearing", "web(NYFed)", "llm-web", "改(升为binding)",
      causal_sentence="SOFR 相对 IORB 走阔即准备金稀缺的 binding 信号 → 经回购市场定价 → 驱动流动性/利率。"),
    E("FRA-OIS 利差", "A", "series", ["liquidity"], "CD",
      "confirming", "web", "llm-web", "新增",
      causal_sentence="FRA-OIS 度量银行间无担保融资的信用/流动性溢价（尾部）→ 经美元融资压力 → 驱动流动性。"),
    E("Fed swap line / SRF / FIMA 动用", "A", "policy", ["liquidity"], "CD",
      "confirming", "web(Fed)", "llm-web", "新增",
      causal_sentence="互换额度/SRF/FIMA 动用即 Fed 投放美元流动性救火（尾部）→ 经离岸美元供给 → 驱动流动性。"),
    E("SLOOS 银行信贷标准", "A", "event", ["liquidity"], "CD",
      "load_bearing", "web(Fed)", "llm-web", "新增", lag="领先(季)",
      causal_sentence="银行信贷标准收紧领先信用收缩 → 经信贷供给传导实体流动性 → 驱动流动性。"),

    # ── 3.3 美国 — 利率市场 / 信用 / 波动率 / 定位 ───────────────────────
    E("2Y/10Y/30Y 国债", "A", "series", ["rates"], "CD",
      "load_bearing", "FRED", "fred-api", "已有",
      causal_sentence="国债收益率是利率体制的直接读数与定价基准 → 直接驱动利率。"),
    E("10Y 实际利率 TIPS", "A", "series", ["rates", "fx"], "CD",
      "load_bearing", "FRED", "fred-api", "已有",
      causal_sentence="10Y 实际利率是全球资产的贴现率与美元套息基础 → 经折现与利差 → 驱动利率与美元。"),
    E("期限溢价 ACM 分解", "B", "series", ["rates"], "CD",
      "confirming", "web(NYFed)", "llm-web", "新增",
      causal_sentence="ACM 把名义利率拆出期限溢价分量 → 经供给/风险定价归因 → 辅判利率成因。"),
    E("2s10s 曲线斜率", "B", "series", ["rates"], "CO",
      "confirming", "FRED", "fred-api", "新增"),
    E("IG OAS", "B", "series", ["liquidity"], "CO",
      "load_bearing", "FRED", "fred-api", "改"),
    E("HY OAS", "B", "series", ["liquidity"], "CO",
      "load_bearing", "FRED", "fred-api", "改(报警序列)",
      alert_series=True, alert_band={"z": 2.0}),
    E("CMBS/ABS OAS(NFCI 最高权重)", "B", "series", ["liquidity"], "CO",
      "confirming", "web", "llm-web", "新增"),
    E("MOVE 债市波动率", "B", "series", ["rates", "liquidity"], "CO",
      "load_bearing", "web", "llm-web", "新增(本对话已加)",
      alert_series=True, alert_band={"z": 2.0}),
    E("VIX", "B", "series", ["liquidity", "fx"], "CO",
      "confirming", "FRED/CBOE", "fred-api", "新增(本对话已加)"),
    E("金融条件指数 FCI(NFCI/GS)", "B", "series", ["liquidity"], "CO",
      "load_bearing", "FRED", "fred-api", "新增(本对话已加)"),
    E("股票估值 CAPE", "C", "series", ["liquidity"], "CO",
      "background", "web", "llm-web", "新增"),
    E("市场内部/breadth+集中度", "B", "series", ["liquidity"], "CO",
      "confirming", "web", "llm-web", "新增"),
    E("AI-capex 体制代理", "C", "policy", ["liquidity", "rates"], "CD",
      "background", "web", "llm-web", "新增",
      causal_sentence="AI 资本开支体制代理增长/通胀的结构性需求与利率敏感性 → 经投资与名义增长 → 影响利率/流动性。"),
    E("持仓拥挤(CFTC + CTA/vol-target + basis-trade规模)", "B", "series",
      ["rates", "fx", "liquidity"], "CD",
      "load_bearing", "web", "llm-web", "新增", lag="同步(carry探头)",
      causal_sentence="拥挤定位是 carry 渠道传感器：拥挤越极端，去杠杆平仓的非线性冲击越大 → 经强制平仓资金流 → 驱动利率/汇率/流动性。"),

    # ── 3.4 美元 / 全球流动性 ────────────────────────────────────────────
    E("广义/EM加权美元(Fed DTWEXBGS)", "A", "series", ["fx", "liquidity"], "CD",
      "load_bearing", "FRED", "fred-api", "新增(替 DXY 做中国FX)",
      causal_sentence="广义美元（贸易加权）是真正作用于中国/EM 的美元强弱 → 经融资条件与贸易渠道 → 驱动汇率/流动性。"),
    E("DXY", "B", "series", ["fx"], "CO",
      "confirming", "FRED", "fred-api", "改(中国侧降B,工具错57%欧元)"),
    E("跨币种基差(EUR/JPY-USD)", "A", "series", ["liquidity", "fx"], "CF",
      "load_bearing", "web", "llm-web", "改(并入流动性逻辑链)",
      alert_series=True, alert_band={"z": 2.0},
      causal_sentence="跨币种基差走负=离岸美元融资紧张，钱抢美元 → 经美元资金渠道 → 驱动流动性与汇率。"),
    E("USDJPY / 日元 carry", "A", "series", ["liquidity", "fx"], "CF",
      "load_bearing", "FRED", "fred-api", "改(标条件触发)",
      alert_series=True, alert_band={"delta": 3.0},
      causal_sentence="日元 carry 平仓时资金回流日元、全球抛风险资产（条件/阈值尾部触发）→ 经跨资产资金搬家 → 驱动流动性与汇率。"),
    E("BoJ 政策 / JGB 收益率", "A", "policy", ["rates", "liquidity", "fx"], "CF",
      "confirming", "web", "llm-web", "新增",
      causal_sentence="BoJ 政策与 JGB 收益率决定日元融资成本，是全球 carry 资金的源头闸门 → 经跨境资金流 → 驱动利率/流动性/汇率。"),
    E("ECB 政策分化 / EUR-USD", "B", "policy", ["fx"], "CF",
      "background", "web", "llm-web", "新增",
      causal_sentence="欧美政策分化驱动 EUR-USD 利差套利资金流 → 经欧元/美元仓位搬家 → 影响汇率。"),
    E("BIS 全球流动性(USD/EUR/JPY 对非银信用)", "B", "event", ["liquidity"], "CD",
      "background", "web(BIS)", "llm-web", "新增", lag="滞后(季)",
      causal_sentence="BIS 全球流动性度量跨境对非银的美元/欧元/日元信用扩张 → 经离岸信用供给 → 驱动流动性。"),
    E("TIC / 外国持美债 + 中国持美债", "B", "event", ["rates", "fx"], "CF",
      "background", "web(Treasury)", "llm-web", "新增", lag="滞后(月)",
      causal_sentence="外国（含中国）增减持美债是跨境资金流读数 → 经对美债需求与美元 → 影响利率/汇率。"),
    E("黄金", "B", "series", ["fx"], "CO",
      "confirming", "FRED", "fred-api", "改(机制纠正,见§5)"),
    E("比特币", "C", "series", ["liquidity"], "CR",
      "background", "web", "llm-web", "已有(确认正确)"),
    E("大宗(铜/铁矿)", "C", "series", ["rates", "fx"], "CO",
      "background", "web", "llm-web", "新增"),

    # ── 3.5 中国 — 增长 / 通胀 ───────────────────────────────────────────
    E("官方制造业 PMI", "A", "event", ["rates", "fx"], "CD",
      "load_bearing", "统计局", "llm-web", "新增", lag="领先",
      causal_sentence="官方 PMI 领先工业增长动能 → 经增长预期影响货币政策与人民币 → 驱动利率与汇率。"),
    E("财新 PMI", "A", "event", ["rates", "fx"], "CD",
      "confirming", "财新", "llm-web", "新增", lag="领先",
      causal_sentence="财新 PMI 侧重中小/出口企业，与官方互补印证增长动能 → 经政策与汇率预期 → 驱动利率与汇率。"),
    E("工业增加值", "A", "event", ["rates"], "CD",
      "confirming", "统计局", "llm-web", "新增",
      causal_sentence="工业增加值是实际产出核心读数 → 经增长动能影响货币政策 → 驱动利率。"),
    E("社会消费品零售", "A", "event", ["rates"], "CD",
      "confirming", "统计局", "llm-web", "新增",
      causal_sentence="社零度量内需消费强弱 → 经增长与通胀路径影响政策 → 驱动利率。"),
    E("固定资产投资", "B", "event", ["rates"], "CD",
      "background", "统计局", "llm-web", "新增",
      causal_sentence="FAI 反映投资驱动的增长动能（含地产/基建）→ 经增长预期 → 影响利率。"),
    E("出口(美元计)", "A", "event", ["fx"], "CD",
      "confirming", "海关总署", "llm-web", "新增",
      causal_sentence="出口决定贸易顺差与结汇供给 → 经经常账户外汇供求 → 驱动汇率。"),
    E("用电量/货运(克强指标)", "B", "event", ["rates"], "CO",
      "background", "web", "llm-web", "新增"),
    E("中国 CPI", "A", "event", ["rates"], "CD",
      "load_bearing", "统计局", "llm-web", "新增",
      causal_sentence="中国 CPI 度量内需通胀/通缩压力 → 经实际利率与政策空间 → 驱动利率。"),
    E("中国 PPI", "A", "event", ["rates", "liquidity"], "CD",
      "load_bearing", "统计局", "llm-web", "新增",
      causal_sentence="PPI 持续为负是工业通缩信号 → 经企业实际利率上升与去杠杆压力 → 驱动利率与流动性需求。"),

    # ── 3.6 中国 — 货币政策 / 利率 ───────────────────────────────────────
    E("7天 OMO 逆回购利率(新锚)", "A", "event", ["rates", "liquidity"], "CD",
      "load_bearing", "PBoC", "llm-web", "改(升为政策锚)",
      causal_sentence="7 天 OMO 利率已升为 PBoC 政策利率新锚 → 经利率走廊传导 DR/LPR → 驱动利率与流动性。"),
    E("MLF 利率", "A", "event", ["rates"], "CD",
      "confirming", "PBoC", "llm-web", "改",
      causal_sentence="MLF 利率是中期政策利率，影响银行边际负债成本 → 经定价传导 → 驱动利率。"),
    E("LPR 1Y/5Y(5Y=房贷链)", "A", "event", ["rates"], "CD",
      "load_bearing", "PBoC", "llm-web", "已有", lag="同步(月)",
      causal_sentence="LPR（5Y 锚定房贷）是贷款定价基准 → 经信贷与房贷成本 → 驱动利率。"),
    E("RRR 存款准备金率", "A", "policy", ["liquidity"], "CD",
      "load_bearing", "PBoC", "llm-web", "新增",
      causal_sentence="降准释放长期可贷资金、降低银行负债成本 → 经准备金供给 → 驱动流动性。"),
    E("DR007/R007", "B", "series", ["liquidity", "rates"], "CO",
      "load_bearing", "CFETS", "llm-web", "已有(纪律:CO→B,见§2.1)",
      alert_series=True, alert_band={"z": 2.0}),
    E("NCD 同业存单利率", "B", "series", ["liquidity", "rates"], "CD",
      "confirming", "CFETS", "llm-web", "新增",
      causal_sentence="NCD 利率反映银行边际负债成本与同业流动性松紧 → 经负债端定价 → 影响利率与流动性。"),
    E("超额准备金率(走廊下限)", "C", "policy", ["rates"], "CO",
      "background", "PBoC", "llm-web", "新增", lag="滞后(季)"),
    E("中国 10Y CGB + 资产荒需求", "A", "series", ["rates", "fx"], "CD",
      "load_bearing", "Chinabond", "llm-web", "改(升级)",
      causal_sentence="10Y CGB 在资产荒下被配置盘抢购压低长端，反映增长/通胀与政策预期 → 经长端定价与中美利差 → 驱动利率与汇率。"),
    E("结构性工具 PSL/再贷款", "A", "policy", ["liquidity"], "CD",
      "confirming", "PBoC", "llm-web", "新增",
      causal_sentence="PSL/再贷款向特定领域定向投放基础货币 → 经结构性信用供给 → 驱动流动性。"),
    E("货币政策执行报告 MPR", "A", "policy", ["rates", "liquidity"], "CD",
      "load_bearing", "PBoC", "llm-web", "新增", lag="滞后(季)",
      causal_sentence="MPR 措辞（如'稳健'松紧、闸门提法）昭示货币政策取向变化 → 经政策预期 → 驱动利率与流动性。"),

    # ── 3.7 中国 — 流动性 / 信用 ─────────────────────────────────────────
    E("社融 TSF", "A", "event", ["liquidity"], "CD",
      "load_bearing", "PBoC", "llm-web", "已有", lag="同步(月)",
      causal_sentence="社融是实体融资总量总闸 → 经信用扩张/收缩 → 驱动流动性。"),
    E("M1/M2/剪刀差", "A", "event", ["liquidity"], "CD",
      "load_bearing", "PBoC", "llm-web", "已有", lag="同步(月)",
      causal_sentence="M1-M2 剪刀差度量资金活化程度（企业现金流意愿）→ 经货币流通速度 → 驱动流动性。"),
    E("信贷脉冲", "A", "event", ["liquidity", "fx"], "CD",
      "load_bearing", "派生", "manual", "已有", lag="领先(月)",
      causal_sentence="信贷脉冲（新增信贷/GDP 变化）领先实体经济与资产价格 → 经信用传导 → 驱动流动性与汇率。"),
    E("贷款增速", "A", "event", ["liquidity"], "CD",
      "confirming", "PBoC", "llm-web", "已有", lag="同步(月)",
      causal_sentence="贷款增速是银行信用投放的直接读数 → 经信用供给 → 驱动流动性。"),

    # ── 3.8 中国 — 汇率 / 资金流 ─────────────────────────────────────────
    E("USDCNY", "B", "series", ["fx"], "CO",
      "load_bearing", "FRED", "fred-api", "已有(纪律:CO→B,见§2.1)"),
    E("PBoC 中间价 + 逆周期因子", "A", "series", ["fx"], "CD",
      "load_bearing", "PBoC/CFETS", "llm-web", "已有(确认为真A)",
      causal_sentence="中间价与逆周期因子是 PBoC 对人民币的政策意图直接表达 → 经管理浮动定价锚 → 驱动汇率。"),
    E("CNH-CNY 价差", "A", "series", ["fx"], "CF",
      "load_bearing", "web", "llm-web", "已有",
      alert_series=True, alert_band={"delta": 0.005},
      causal_sentence="CNH-CNY 价差走阔反映离岸贬值/资金外流压力 → 经离岸-在岸套利资金流 → 驱动汇率。"),
    E("CNH HIBOR/离岸流动性 + 央行 HK 票", "A", "series", ["fx", "liquidity"], "CF",
      "confirming", "HKMA", "llm-web", "新增",
      causal_sentence="抬升 CNH HIBOR/发离岸央票收紧离岸人民币流动性以抬高做空成本 → 经离岸资金渠道 → 驱动汇率与流动性。"),
    # 「结售汇 + 外汇占款 + 代客涉外收付」拆成 3 条脚本数值项（各自独立 observed.value）：
    # 结售汇差额/涉外收付差额走新建 SAFE-Excel 通道、外汇占款走 akshare。fetch 配置块（safe/akshare）
    # 由 live upsert 富化（同其余脚本项），seed 仅记粗粒度框架行。
    E("银行结售汇差额", "A", "series", ["fx"], "CF",
      "load_bearing", "SAFE", "safe", "拆分(\"最大遗漏\";脚本化)", lag="滞后(月)",
      causal_sentence="银行结售汇差额=企业/居民经银行的净结汇（结汇−售汇）实际购售汇净额 → 直接计量境内外汇供求 → 驱动汇率。"),
    E("银行代客涉外收付差额", "A", "series", ["fx"], "CF",
      "load_bearing", "SAFE", "safe", "拆分(脚本化)", lag="滞后(月)",
      causal_sentence="银行代客涉外收付差额=银行代客户的跨境收入−支出净额，计量实际跨境资金净流入流出 → 经外汇供求 → 驱动汇率。"),
    E("外汇占款", "B", "series", ["fx"], "CF",
      "confirming", "PBoC", "akshare", "拆分(akshare 脚本化)", lag="滞后(月)",
      causal_sentence="外汇占款=央行购汇投放的基础货币存量，其月度增减反映结售汇净额经央行的沉淀 → 经外汇供求与基础货币 → 驱动汇率与流动性。"),
    E("外汇储备(水平+变动)", "A", "event", ["fx"], "CF",
      "load_bearing", "SAFE", "llm-web", "新增", lag="滞后(月)",
      causal_sentence="外储变动（剔除估值）反映央行干预与资金净流出规模 → 经官方外汇供求 → 驱动汇率。"),
    E("中美 10Y 利差", "B", "series", ["fx"], "CO",
      "confirming", "派生", "manual", "改(A→B,见§5)"),
    E("中美实际利率差", "B", "series", ["fx"], "CF",
      "background", "派生", "manual", "新增",
      causal_sentence="中美实际利率差影响套息资金的跨境配置方向 → 经利差套利资金流 → 影响汇率。"),
    E("北向资金", "A", "series", ["fx", "liquidity"], "CF",
      "load_bearing", "HKEX", "llm-web", "已有",
      causal_sentence="北向资金是境外配置 A 股的跨境资金流 → 经股市资金与结汇 → 驱动汇率与流动性。"),
    E("南向港股通", "A", "series", ["fx", "liquidity"], "CF",
      "load_bearing", "HKEX", "llm-web", "新增",
      causal_sentence="南向资金是境内配置港股的换汇外流 → 经购汇与离岸人民币供给 → 驱动汇率与流动性。"),
    E("外资持 CGB(债券通)", "B", "event", ["rates", "fx"], "CF",
      "confirming", "Chinabond", "llm-web", "新增", lag="滞后(月)",
      causal_sentence="外资增减持中国国债是债市跨境资金流 → 经对 CGB 需求与结售汇 → 影响利率与汇率。"),
    E("远期售汇风险准备金率", "B", "policy", ["fx"], "CD",
      "background", "PBoC", "llm-web", "新增",
      causal_sentence="上调远期售汇风险准备金率抬高购汇远期成本以抑制贬值预期 → 经购汇成本 → 影响汇率。"),
    E("CFETS 人民币篮子指数", "B", "series", ["fx"], "CO",
      "background", "CFETS", "llm-web", "新增", lag="同步(周)"),
    E("出口商结汇率", "B", "event", ["fx"], "CF",
      "confirming", "SAFE", "llm-web", "新增", lag="滞后(月)",
      causal_sentence="出口商结汇率高低决定顺差转化为实际外汇供给的比例 → 经结汇资金流 → 影响汇率。"),
    E("ADR/H 股溢价折价", "B", "series", ["fx"], "CF",
      "background", "web", "llm-web", "新增",
      causal_sentence="ADR/H 股相对 A 股的溢折价反映跨市场套利与离岸资金偏好 → 经跨境定价资金流 → 影响汇率。"),
    E("FDI 月度", "B", "event", ["fx"], "CD",
      "background", "商务部", "llm-web", "新增", lag="滞后(月)",
      causal_sentence="FDI 是直接投资项下的长期资金流入 → 经资本项外汇供求 → 影响汇率。"),
    E("中国专项基金 EPFR(非宽EM)", "B", "event", ["fx", "liquidity"], "CF",
      "confirming", "web(EPFR)", "llm-web", "新增", lag="同步(周)",
      causal_sentence="专投中国（非泛 EM）的基金申赎是配置盘对中国资产的跨境资金流 → 经组合资金流 → 影响汇率与流动性。"),
    E("MSCI/FTSE 中国权重调整", "B", "policy", ["fx"], "CD",
      "background", "web", "llm-web", "新增",
      causal_sentence="指数纳入/权重调整触发被动配置盘的机械性买卖 → 经被动资金流 → 影响汇率。"),

    # ── 3.9 中国 — 地产 / 财政（信用传导阀）──────────────────────────────
    E("30 城新房成交(高频)", "B", "series", ["liquidity"], "CO",
      "load_bearing", "CREIS/Wind", "llm-web", "已有(高频化;纪律:CO→B,见§2.1)"),
    E("二手房价/成交", "B", "series", ["liquidity"], "CO",
      "confirming", "中指/统计局", "llm-web", "新增(纪律:CO→B,见§2.1)"),
    E("70 城房价", "A", "event", ["rates", "liquidity"], "CD",
      "load_bearing", "统计局", "llm-web", "新增", lag="滞后(月)",
      causal_sentence="70 城房价趋势决定居民资产负债表与抵押品价值 → 经财富效应与信贷抵押链 → 驱动利率与流动性。"),
    E("房地产开发投资", "B", "event", ["liquidity"], "CD",
      "confirming", "统计局", "llm-web", "新增", lag="滞后(月)",
      causal_sentence="地产开发投资是信用需求与上下游融资链条的核心 → 经信贷传导 → 驱动流动性。"),
    E("土地出让金", "A", "event", ["liquidity"], "CD",
      "confirming", "财政部", "llm-web", "新增", lag="滞后(月)",
      causal_sentence="土地出让金是地方政府性基金收入主体，下滑收紧地方财政与投资 → 经财政信用传导 → 驱动流动性。"),
    E("开发商美元债/地产高收益", "A", "series", ["fx", "liquidity"], "CD",
      "confirming", "web", "llm-web", "新增",
      causal_sentence="开发商美元债利差走阔=离岸再融资关闭与违约风险 → 经地产信用与离岸美元需求 → 驱动汇率与流动性。"),
    E("地方专项债发行", "A", "event", ["liquidity"], "CD",
      "confirming", "财政部", "llm-web", "已有", lag="同步(月)",
      causal_sentence="专项债发行节奏决定基建财政投放与对流动性的抽取/释放 → 经财政资金投放 → 驱动流动性。"),
    E("财政存款", "B", "event", ["liquidity"], "CD",
      "background", "财政部", "llm-web", "已有", lag="同步(月)",
      causal_sentence="财政存款增减（缴税/支出节奏）吸放银行体系流动性 → 经基础货币 → 驱动流动性。"),
    E("LGFV/城投利差(TSF 质量过滤器)", "B", "series", ["liquidity"], "CF",
      "confirming", "Wind", "llm-web", "新增",
      causal_sentence="城投利差走阔反映地方隐性债务再融资压力，作为社融质量过滤器 → 经信用风险定价与资金流 → 影响流动性。"),

    # ── 3.10 跨切 / 类别尾部（always-alert）──────────────────────────────
    E("中美地缘/关税", "A", "policy", ["fx", "liquidity"], "CD",
      "load_bearing", "web", "llm-web", "新增",
      causal_sentence="地缘/关税升级冲击贸易顺差与风险偏好（always-alert，无市场序列可 diff）→ 经贸易与避险渠道 → 驱动汇率与流动性。"),
    E("ADR 退市/HFCAA/PCAOB", "A", "policy", ["fx", "liquidity"], "CD",
      "load_bearing", "web", "llm-web", "新增",
      causal_sentence="ADR 退市/审计监管升级触发中概股资金回撤与离岸抛压 → 经跨境股权资金流 → 驱动汇率与流动性。"),
    E("美出口管制/实体清单", "A", "policy", ["liquidity"], "CD",
      "confirming", "web", "llm-web", "新增",
      causal_sentence="出口管制/实体清单冲击相关企业融资与产业链信用 → 经行业信用与风险偏好 → 驱动流动性。"),
    E("资本管制/SAFE 出境规则", "A", "policy", ["fx"], "CD",
      "confirming", "web", "llm-web", "新增",
      causal_sentence="资本管制/出境规则收紧直接限制资金外流 → 经资本项外汇供求 → 驱动汇率。"),
    E("中国政治局/NPC 经济信号", "A", "policy", ["rates", "liquidity"], "CD",
      "load_bearing", "web", "llm-web", "新增",
      causal_sentence="政治局/NPC 定调财政货币与刺激力度 → 经政策预期与信用扩张 → 驱动利率与流动性。"),
    E("CSRC 监管动作", "B", "policy", ["liquidity"], "CD",
      "confirming", "web", "llm-web", "新增",
      causal_sentence="证监会监管动作（IPO/减持/再融资节奏）影响股市资金供求 → 经市场流动性 → 影响流动性。"),
    E("美财政/债务上限/财政主导", "A", "policy", ["rates", "liquidity"], "CD",
      "confirming", "web", "llm-web", "新增",
      causal_sentence="债务上限/财政主导风险冲击国债供给与无风险资产信用 → 经期限溢价与流动性 → 驱动利率与流动性。"),
    E("中国主权评级展望", "B", "policy", ["rates", "fx"], "CD",
      "background", "web", "llm-web", "新增",
      causal_sentence="主权评级展望调整影响中国资产风险溢价与外资配置意愿 → 经风险定价 → 影响利率与汇率。"),
]


def main():
    try:
        mr.read_registry(SLUG, VARIANT)
    except FileNotFoundError:
        mr.create_registry(SLUG, VARIANT)
    for e in INPUTS:
        mr.upsert_input(SLUG, VARIANT, e)
    errors = mr.validate_registry(SLUG, VARIANT)
    print(f"seeded {len(INPUTS)} inputs; validator errors: {len(errors)}")
    for err in errors:
        print("  ✗", err)


if __name__ == "__main__":
    main()
